### ISSUE TITLE
Improve helm chart infrastructure configuration

### ISSUE THREAD

**Issue by dejanb** [trustification/trustification#1122]
There are still a few places where infrastructure settings in helm charts can be improved.

1. Walkers jobs and UI deployments try to set annotations and labels for metrics/tracing even if it not defined in schema that they can be enabled. This works fine for now but preventing further refactoring. We should either enable them or remove/change label/annotation settings.

2. Currently infra, metrics and tracing are set independently

```
infrastructure:
  port: 9010

metrics:
  enabled: false

tracing:
  enabled: false
```

If we end up assuming that all modules that have infra can have metrics and tracing, it would be clearer to set it all using the same root config, something like:

```
infrastructure:
  enabled: true
  port: 9010
  metrics:
    enabled: false
  tracing:
     enabled: false
```
